# For use with github-labeler: https://github.com/marketplace/actions/github-labeler

- name: "bug"
  color: "B60205"
  description: "Something isn't working"
- name: "chore"
  color: "FBCA04"
  description: "Backend change that doesn't affect users"
- name: "ci"
  color: "FBCA04"
  description: "This affects the CI/CD pipeline"
- name: "docs"
  color: "5319E7"
  description: "Documentation improvements"
- name: "duplicate"
  color: "BFD4F2"
  description: "This topic already exists"
- name: "enhancement"
  color: "1D76DB"
  description: "New feature or improvement to an existing one"
- name: "help wanted"
  color: "BFD4F2"
  description: "Contributions are welcome"
- name: "pr-breaking"
  color: "B60205"
  description: "This PR introduces a breaking change! A major release will be required"
- name: "pr-bugfix"
  color: "0E8A16"
  description: "This PR introduces a bugfix (-> patch release)"
- name: "pr-feature"
  color: "0052CC"
  description: "This PR introduces a feature or enhancement (-> minor release)"
- name: "pr-nochangelog"
  color: "F9D0C4"
  description: "Do not record this PR in the changelog. Overrides other 'pr-' labels"
- name: "question"
  color: "0052cc"
  description: "Something is unclear"
- name: "waiting for feedback"
  color: "5319E7"
  description: "This is waiting for a response"
- name: "wontfix"
  color: "000000"
  description: "This is a valid problem that can/will not be fixed"
