authors:
- Max Hösel <ansible@maxhoesel.de>
build_ignore:
- .circleci
- .github
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- pyproject.toml
- tox.ini
- .yamllint
- .ansible-lint
- .pre-commit-config.yaml
- '*.tar.gz'
- .venv
- .tox
- .pytest_cache
- scripts
- requirements.txt
- requirements-molecule.txt
- '**/requirements-molecule.txt'
- '**/requirements.txt'
dependencies: {}
description: Mangage Smallstep CA servers
issues: https://github.com/maxhoesel-ansible/ansible-collection-smallstep/issues
license:
- GPL-3.0-or-later
license_file: ''
name: smallstep
namespace: maxhoesel
readme: README.md
repository: https://github.com/maxhoesel-ansible/ansible-collection-smallstep
tags:
- smallstep
- ca
- certificates
version: 0.24.0
