authors:
- Max Hösel <ansible@maxhoesel.de>
build_ignore:
- '*.tar.gz'
- .venv*
- .github
- .tox
- .pytest_cache
- scripts
- docs
dependencies: {}
description: Mangage Smallstep CA servers
issues: https://github.com/maxhoesel-ansible/ansible-collection-smallstep/issues
license:
- GPL-3.0-or-later
license_file: ''
name: smallstep
namespace: maxhoesel
readme: README.md
repository: https://github.com/maxhoesel-ansible/ansible-collection-smallstep
tags:
- smallstep
- ca
- certificates
version: 0.23.0
