---
- name: Look for existing step-ca binary
  stat:
    path: "{{ step_ca_executable }}"
  register: step_ca_present
- name: Get currently installed step-ca version
  shell: >
    set -o pipefail &&
    {{ step_ca_executable }} version | cut -d' ' -f 2 | cut -d'/' -f 2 | awk 'FNR == 1'
  args:
    executable: /bin/bash
  changed_when: no
  check_mode: no
  register: step_ca_installed_version
  when: step_ca_present.stat.exists

- name: Download and install step-ca
  block:
    - name: Download and extract step-ca archive
      unarchive:
        src: "https://github.com/smallstep/certificates/releases/download/v{{ step_ca_version }}/step-ca_linux_{{ step_ca_version }}_{{ step_ca_arch[ansible_architecture] }}.tar.gz"
        dest: /tmp/
        remote_src: yes
      retries: 3
      delay: 3
    - name: Install step-ca binary <0.23 # noqa no-changed-when
      shell: >
        set -o pipefail &&
        mv -Z /tmp/step-ca_{{ step_ca_version }}/bin/* {{ step_ca_executable | dirname }}
      args:
        executable: /bin/bash
      notify: restart step-ca
      when: step_ca_version is version("0.23", "<")
    - name: Install step-ca binary >=0.23 # noqa no-changed-when
      shell: >
        set -o pipefail &&
        mv -Z /tmp/step-ca_{{ step_ca_version }}/step-ca {{ step_ca_executable | dirname }}
      args:
        executable: /bin/bash
      notify: restart step-ca
      when: step_ca_version is version("0.23", ">=")
  always:
    - name: Remove step release archive
      file:
        path: "/tmp/step-ca_{{ step_ca_version }}"
        state: absent
  when: (step_ca_installed_version.stdout) | default("") != step_ca_version
