- name: Get latest step-ca release information
  ansible.builtin.uri:
    url: https://api.github.com/repos/smallstep/certificates/releases/latest
    body_format: json
    return_content: yes
  register: step_ca_latest_release
  delegate_to: localhost
  become: no
  run_once: yes
- name: Set latest release version
  ansible.builtin.set_fact:
    step_ca_version: "{{ (step_ca_latest_release.json.tag_name)[1:] }}"
