version: 2.1

orbs:
  collection-testing: maxhoesel-ansible/ansible-collection-testing@0.6.3

filters: &semver-tagged
  tags:
    only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*).*$/
  branches:
    ignore: /.*/

workflows:
  ci:
    jobs:
      - collection-testing/pytest:
          name: "Pytest (<< matrix.pytest_args >>, << matrix.uv_sync_args >>)"
          parallelism: 3
          matrix:
            parameters:
              pytest_args:
                - --node-python-version 3.9 --step-cli-version 0.24.0 --step-ca-version 0.24.0
                - --node-python-version 3.9 --step-cli-version latest --step-ca-version latest
              uv_sync_args:
                - --group ansible-2.20
                - --group ansible-2.21
      - collection-testing/pre-commit-lint:
          name: Lint
      - collection-testing/antsibull-docs:
          name: Generate Docs
      - collection-testing/publish-github:
          name: Publish Release to GitHub
          context: collection-publishing
          filters: *semver-tagged
      - collection-testing/publish-galaxy:
          name: Publish to Galaxy
          context: collection-publishing
          filters: *semver-tagged
