---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get running services
      service_facts:

    - name: Verify that step-ca service is running and enabled
      assert:
        that:
          - ansible_facts.services["step-ca.service"].state == "running"
          - ansible_facts.services["step-ca.service"].status == "enabled"

    - name: Test step ca health
      command: step-cli ca health
      become: yes
      become_user: "{{ step_ca_user }}"
      changed_when: no
