---
- name: Converge
  hosts: clients
  vars:
    webroots:
      Debian: /var/www/html
      RedHat: /usr/share/nginx/html
    webgroup:
      Debian: www-data
      RedHat: nginx
  tasks:
    - name: Test getting a standalone cert
      include_role:
        name: step_acme_cert

    - name: Start nginx
      systemd:
        name: nginx
        state: started

    - name: Get cert via webroot
      include_role:
        name: step_acme_cert
      vars:
        step_acme_cert_webroot_path: "{{ webroots[ansible_os_family] }}"
        step_acme_cert_duration: 1h
        step_acme_cert_renewal_service: step-renew-webroot
        step_acme_cert_renewal_when: 59m # force renewal to happen every minute
        step_acme_cert_renewal_reload_services: ["nginx"]

    - name: Install Nginx site [Debian]
      template:
        src: ../templates/nginx_site.conf
        dest: /etc/nginx/sites-enabled/default
        owner: root
        group: root
        mode: "644"
      notify: restart nginx
      when: ansible_os_family == "Debian"
    - name: Install Nginx config [RedHat]
      template:
        src: ../templates/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: "644"
      notify: restart nginx
      when: ansible_os_family == "RedHat"
  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
