---
- name: Load Distribution-specific vars
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
- name: Set variables
  ansible.builtin.set_fact:
    step_cli_install_path: "{{ ('/' in step_cli_executable) | ternary(step_cli_executable, step_cli_install_dir + '/' + step_cli_executable) }}"

- name: Install dependencies
  ansible.builtin.include_tasks: prepare_deps.yml
- name: Determine latest compatible version
  ansible.builtin.include_tasks: prepare_latest_compat_release.yml
  when: step_cli_version == "latest-compat"
- name: Determine latest version
  ansible.builtin.include_tasks: prepare_latest_release.yml
  when: step_cli_version == "latest"

- name: Install step-cli
  ansible.builtin.include_tasks: install_cli.yml

- name: Configure step-cli capabilities
  ansible.builtin.include_tasks: configure_capabilities.yml
