#!/usr/bin/env python3

# update the version number of this collection to the specified value.
# Usage: ./update-version x.y.z

import argparse
import copy
from packaging import version
import yaml


def update_galaxy_yml(ver):
    with open("galaxy.yml", encoding="utf-8") as f:
        galaxy = yaml.safe_load(f)

    new_galaxy = copy.deepcopy(galaxy)
    new_galaxy["version"] = str(ver)

    if new_galaxy != galaxy:
        with open("galaxy.yml", "w", encoding="utf-8") as f:
            yaml.dump(new_galaxy, f, allow_unicode=True)


def update_util_collection_version(ver):
    with open("plugins/module_utils/constants.py", encoding="utf-8") as f:
        data = f.readlines()

    data = list(map(lambda line: f'COLLECTION_VERSION = "{ver}"' if line.startswith(
        "COLLECTION_VERSION") else line.rstrip(), data))

    with open("plugins/module_utils/constants.py", "w", encoding="utf-8") as f:
        f.write("{}\n".format('\n'.join(data).rstrip()))


def update_step_ca_collection_version(ver):
    with open("roles/step_ca/vars/main.yml", encoding="utf-8") as f:
        data = f.readlines()

    data = map(lambda line: f'smallstep_collection_version: "{ver}"' if line.startswith(
        "smallstep_collection_version: ") else line.rstrip(), data)

    with open("roles/step_ca/vars/main.yml", "w", encoding="utf-8") as f:
        f.write("{}\n".format('\n'.join(data).rstrip()))


def update_step_cli_collection_version(ver):
    with open("roles/step_cli/vars/main.yml", encoding="utf-8") as f:
        data = f.readlines()

    data = map(lambda line: f'smallstep_collection_version: "{ver}"' if line.startswith(
        "smallstep_collection_version: ") else line.rstrip(), data)

    with open("roles/step_cli/vars/main.yml", "w", encoding="utf-8") as f:
        f.write("{}\n".format('\n'.join(data).rstrip()))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("version", help="Version number to set")
    args = parser.parse_args()

    ver = version.parse(args.version.strip("v"))

    update_galaxy_yml(ver)
    update_util_collection_version(ver)
    update_step_ca_collection_version(ver)
    update_step_cli_collection_version(ver)


if __name__ == "__main__":
    main()
