argument_specs:
  main:
    short_description: Install the C(step-cli) tool on a host.
    description:
      - This role is used by R(step_bootstrap_host,ansible_collections.maxhoesel.smallstep.step_bootstrap_host_role) and R(step_ca,ansible_collections.maxhoesel.smallstep.step_ca_role), but can also be used standalone to install the cli tool and then do nothing else.
      - |
        Requirements:

        - Root access using C(become: yes) or equivalent
      - |
        Supported distributions:

        - Ubuntu 18.04 LTS or newer
        - Debian 10 or newer
        - Fedora 36 or newer
        - A CentOS-compatible distribution like RockyLinux/AlmaLinux 8 or newer. RockyLinux is used for testing
      - "Supported architectures: amd64, arm64"
    options:
      step_cli_executable:
        type: path
        description:
          - What to name and where to put the C(step-cli) executable that will be installed by this role
          - Can be an absolute path (make sure that the parent directory is in C($PATH)) or a filename
          - If this executable is not found and I(step_cli_executable) is a B(path), the executable will be installed there
          - If this executable is not found and I(step_cli_executable) is a B(name), the executable will be installed at I(step_cli_install_dir) with the given name
        default: step-cli
      step_cli_version:
        type: str
        default: latest-compatible
        description:
          - Set the version of C(step-cli) to install
          - Can be a version tag (e.g. C(0.15.3)), C(latest), or C(latest-compatible)
          - If set to C(latest-compatible), the most recent compatible release is installed, that is, the most recent minor release that matches the collection minor version.
            For example, if the collection version is C(0.24.x), then the most recent release from the C(0.24) series will be installed.
            See U(https://github.com/maxhoesel-ansible/ansible-collection-smallstep/tree/main#versioning-policy) for more details.
          - If set to C(latest), the most recent version of C(step-cli) is installed, regardless of compatibility with the collection.
            This can be useful if you just want to install C(step-cli), but don't plan on using it with this collection.
            Using minor versions of C(step-cli)/C(step-cli) that don't match the collection minor version is not supported!
          - Note that the role will query the GitHub API if this value is set to C(latest) or C(latest-compatible).
            If you are getting rate limit errors, you can set I(step_cli_version) to a specific value or set I(step_cli_github_token) to a token with higher rate limits
      step_cli_install_dir:
        type: path
        default: "/usr/bin"
        description:
          - Used if the binary defined by I(step_cli_executable) is not found on the system and I(step_cli_executable) contains a executable name
          - Sets the directory to install I(step_cli_executable) into
          - The directory must already exist
          - Ignored if I(step_cli_executable) contains a directory already
