---
# tasks file for step_acme_cert
- include: check.yml

- name: Look for existing certificate
  stat:
    path: "{{ step_acme_cert_certfile.path }}"
  register: step_acme_cert_current_cert

- name: Check if certificate is valid
  changed_when: no
  command: "step-cli certificate verify {{ step_acme_cert_certfile.path }}"
  ignore_errors: true
  register: _step_acme_cert_validity
  when: step_acme_cert_current_cert.stat.exists

- include: get_cert.yml
  when: 'not step_acme_cert_current_cert.stat.exists or "failed to verify certificate" in _step_acme_cert_validity.stderr'

- include: renewal.yml
