---
dependency:
  name: galaxy

driver:
  name: podman

provisioner:
  name: ansible
  env: {}
    # Cannot enable pipelining for podman at this time:
    # https://github.com/ansible-community/molecule-podman/issues/2
    #ANSIBLE_PIPELINING: false

scenario:
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check  # also run check mode in regular tests
    - side_effect
    - verify
    - destroy

verifier:
  name: ansible
