name: Lint Commit Messages
on: [pull_request, push]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Set up pip
        run: pip3 install --upgrade pip
      - name: Install Gitint
        run: pip3 install gitlint
      - name: Run Gitlint
        run: gitlint --commits=2a4983a..HEAD
