---
name: Prepare Release
on:
  push:
    branches:
      - 'release_**'

jobs:
  prepare-release:
    name: "Prepare Release"
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          wget https://github.com/git-chglog/git-chglog/releases/download/v0.11.2/git-chglog_0.11.2_linux_amd64.tar.gz -O git-chglog.tar.gz
          tar xf git-chglog.tar.gz

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"

      - name: Get release version
        run: |
          echo "release_version=$(cat galaxy.yml | grep version: | cut -d ' ' -f 2)" >> $GITHUB_ENV

      - name: Generate full changelog
        run: "./git-chglog --next-tag v${{ env.release_version }} --output CHANGELOG.md"

      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          git commit -m "docs: updated changelog for v${{ env.release_version }}"
          git push

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          pr_title: "Release ${{ env.release_version }}"
          pr_body: "(This release PR was automatically generated via GitHub Actions)"
          github_token: ${{ secrets.GITHUB_TOKEN }}
